os: linux
dist: focal
language: go
go:
- 1.16  # Bazel still uses its own version
env:
  global:
  - BAZEL_VERSION=4.0.0
  - BAZEL_SHA256=bd7a3a583a18640f58308c26e654239d412adaa833b6b6a7b57a216ab62fabc2
before_install:
- |
  wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh"
  echo "${BAZEL_SHA256}  install.sh" | sha256sum -c
  chmod +x install.sh
install:
- |
  ./install.sh --user
  rm -f install.sh
script:
- |
  travis_wait bazel build --config=ci //...
  bazel run //:unifibackup -- --version
before_deploy:
- |
  mkdir out
  bin/release out
deploy:
  provider: releases
  edge: true
  file_glob: true
  file: out/*
  token:
    secure: Nw/Q2hWMw+103mZl+yoaOT+N9duT0fA2Jq3EBuEwe83qLcM4Yj8s1RHESeEiKQuxVKv7PpWn/fPL2vBpRQc0mDo5YMu7v1uGdhT393ZIPKTBZyzOHgl68KFhb+QiTIAb2BWL5lmFl12p0AbnDwCMwibgA9Gw1O0eAfQTTODDaou0+aWK5f1ht/wj3sdYIjVFhlj3Pq4pIIJxvttvNnx3xmoRHALT1cRG9TtVnlM/avBK2hI04T0bBBwjVyuSs5kFNkqmTdSe2fpraYsHPJOZXCg3gWaeYHuNshjawWPef9dRT4Diwkk57SlC2Hu34ehM4b3nYjId3np892VA9p2RbAgA5bg3xNQtrYTd8VXz4oGNwVU6UIKRmqsU+76itqC4znMxyNXxqYAD75N4j88ITiD5hBimDgX4yTSgu4dIvRV+53u4nmkQOjrEzgv2VHsniEwf15VK650M82V1MGCahftQovb/SYie71EDGTd7hcwssFyMGn4LHRTdy4GD70bqVllN1RaxVDde5oyBpJTeD4ag2SFjZHWwDkVr2faR+BF0TVRc2AUcRDjZoaZunnjZA4CL8Q58gOZN0V7UwROSfCCTmXDbMYiURF0/NQlfi7VDIHwhOH9ngwak15jkSAiy6Lt5OqhS5MZtS6TPVFRhGeuIhXQ5lP7LwNeBtlnprF8=
  on:
    repo: gebn/unifibackup
    tags: true
