os: linux
language: shell  # N.B. Bazel downloads its own Go SDK
env:
  global:
    - BAZEL_VERSION=1.2.1
    - BAZEL_SHA256=ae6249e25b0f5a06d79fad90325477dd56275657951cf7aa6a3cbcd79fc4d749
before_install:
  - |
    wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh"
    echo "${BAZEL_SHA256}  install.sh" | sha256sum -c
    chmod +x install.sh
install:
  - |
    ./install.sh --user
    bazel shutdown  # prevents "WARNING: Running Bazel server needs to be killed, because the startup options are different."
    rm -f install.sh
script:
  - |
    bazel \
      --host_jvm_args=-Xmx7000m \
      --host_jvm_args=-Xms7000m \
      build \
      --config=ci \
      --noshow_progress \
      --noshow_loading_progress \
      --local_resources=7500,2,1.0 \
      //...
  - bazel-bin/linux_amd64_static_pure_stripped/unifibackup --version
deploy:
  provider: releases
  file: bazel-bin/linux_amd64_static_pure_stripped/unifibackup
  skip_cleanup: true
  api_key:
    secure: FDVGVW1ZfdGl0RXt3H9mZHEnDbEsEs4zR2cr7EZn4WfNwLDNyJpalCG/+qhElerk3jSn8YrWeqMN1Yn+bpwgSiR9jD53GZGG3QFnvVpnvcTSKrQWkZfDtreJ3etXhdtkKqChDWKM353TQSvlCHAlRmzZ6kZUK+ENqOHA5rBbe9VUJyOG/oUYukzw6IzJmE+v1+AtCRK4YkE+WicvTzw6eeXCqR8+WgGfh8dVxF2sKln0ApgMn8Ax7A9tzKLJBqVDHqr4E7F3HtzFGZk94bS4e4Bu75vXdEUYmt3pxQEWAh+/ChY6wwiO+qech5/b5fWQ44gLpls0cfIgjNw+zmq8rp/sp7jytGm3e2nXb1RUrpOKa5LpdmYB7qC4kpGnfs1OVN8ikT797EfqV5kHNMmIKCdEWKYax0q9CrZ2g9evJXDlF4BayCeOrGycL6kxGhPjqsgdliCI3aOia91nz2NaA09H2PBGX1TAnQLV6R1DIpW/9unmYJTeFqnW4yo8F25e6fUdSOyb9jp3Ne2ybPJ7mUwC3WwwrfOt91wfp0dgBbRKhJ4KOnrj+e8JAtDWkaWw1/+c8xiaC3RGbjKHK8rPnz//BPxznH5OLFKU0n/FgEKwxRmmdJhos9PeMnZidpiseq1R/UhrYmUHTFGVnLV3LKJsv9IfThbQl88gd6Cwaaw=
  on:
    repo: gebn/unifibackup
    tags: true
