name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows, linux, darwin]
        goarch: [amd64, arm64]
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      CGO_ENABLED: 0  # static binary
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.20.1
    - run: make dist
    - id: vars
      run: echo "::set-output name=distpath::$(make distpath)"
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.vars.outputs.distpath }}
        path: ${{ steps.vars.outputs.distpath }}
    - run: sha256sum ${{ steps.vars.outputs.distpath }} > ${{ steps.vars.outputs.distpath }}.sha256
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.vars.outputs.distpath }}.sha256
        path: ${{ steps.vars.outputs.distpath }}.sha256
  containerise:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - uses: actions/download-artifact@v3
      with:
        path: artifacts
    - run: |
        mkdir dist
        ls -lhR artifacts/
        mv artifacts/*.tar.gz/* dist/  # ignore Windows and checksums
    - run: python3 bin/artifact_docker_reorg.py dist/ docker/
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        username: gebn
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - id: vars
      run: echo "::set-output name=tag::$(make tag)"
    - uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: gebn/unifibackup:${{ steps.vars.outputs.tag }}
  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/download-artifact@v3
      with:
        path: artifacts
    - uses: softprops/action-gh-release@v1
      with:
        draft: true
        prerelease: ${{ contains(github.ref, '-') }}
        files: |
          artifacts/*/*
